apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rms-api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rms-api-gateway
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rms-risk-evaluation-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rms-risk-evaluation-service
  minReplicas: 3
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 55
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rms-auth-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rms-auth-service
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rms-gateway-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: rms-api-gateway

