apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rms

resources:
  - ../../infrastructure/k8s/rms-stack.yaml
  - ../../infrastructure/k8s/observability-stack.yaml
  - infra.yaml
  - auth-service.yaml
  - autoscaling.yaml
  - ingress.yaml

