receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

processors:
  batch: {}

exporters:
  debug:
  jaeger:
    endpoint: rms-jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - jaeger
        - debug
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
        - debug
